

spring:
  application:
    name: hardware_api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_user_manage?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    template:
      cache: false
    mode: LEGACYHTML5
    cache-period: 0
  mvc:
    static-path-pattern: /**
server:
  port: 8008
  context-path: /



