server:
  port: 9000

eureka:
  #  instance:
  #    hostname: localhost
  server:
    enable-self-preservation: false #是否开始自我保护机制，如果服务提供者在规定的90秒内没有收到心跳，但在15分钟内收到心跳数大于应该收到数量的85%，剔除服务不会剔除，设置false，关闭自我保护，方便开发与测试
    eviction-interval-timer-in-ms: 4000 #每隔4000毫秒进行一次服务剔除
  client:
    register-with-eureka: false #是否向将自己注册到注册中心（其它的注册中心）
    fetch-registry: false #是否从其它eureka中获取注册信息
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #eureka服务地址
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中注册服务id
    prefer-ip-address: false  #ip地址作为注册名
spring:
  application:
    name: eureka-server-center